name: flutter_portfolio_1
description: Single-page portfolio app
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  connectivity_plus: ^4.0.0
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
